# add the configs for produciton
version: "3"
services:
  nginx:
    ports:
      - "80:80"
  node-app:
    # override BUILD in Dockerfile
    build:
      context: .
      args: 
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node index.js