# add the configs for development
version: "3"
services:
  node-app:
    # override BUILD in Dockerfile
    build:
      context: .  # workdir
      args: 
        NODE_ENV: development
    volumes:
    - ./:/app
    - /app/node_modules  # anonymous volume: it is not synced with host after building
    environment:
      - NODE_ENV=development
      - MONGO_USER=admin
      - MONGO_PASSWORD=admin
      - SESSION_SECRET=secret
    command: npm run dev # override the CMD of Dockerfile
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin