version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app:ro
      - /app/node_modules # anonymous volume: it is not synced with host
    environment:
      - PORT:3000
    # env_files:
    #   - ./.env