# add the  configs that are shared between prods and dev environments
version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  node-app:
    build: .  # build the custom image we have configured in Dockerfile
    environment:
      - PORT=3000
    depends_on:
      - mongo # this makes mongo service runs first to avoid conflicts

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis

volumes:
  mongo-db: 